source 'https://github.com/CocoaPods/Specs.git'

target 'ZHGreenFuture' do
	platform:ios, '6.0'

#pod 'FEFramework',:git => 'git@github.com:FerrariXX/FEFramework.git'
    pod "SDWebImage",               '3.6.0'  #"SDWebImage/WebP"
    pod "AFNetworking",             '2.4.1'
    pod "SVPullToRefresh"
#pod "JSONKit",					'1.5pre'
    pod "DBCamera",                 '2.3.2'
    pod "SVPullToRefresh",          '0.4.1'
    pod "HMSegmentedControl",       '1.4.0'
    pod "ASProgressPopUpView",      '0.8'
    pod "TPKeyboardAvoiding",       '1.2.4'
    pod "ZBarSDK",                  '1.3.1'
    pod "SVProgressHUD",            '1.0'
end
